# name: Deploy to dev environment
# on:
#   push:
#     branches: [ main ]

# jobs:
#   redeploy_everything:
#     runs-on: ubuntu-latest
#     name: Deploying everything to the staging cluster
#     steps:
#       - run: |
#           echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
#           mkdir -p /home/runner/.ssh
#           ls /home/runner/.ssh
#           touch /home/runner/.ssh/known_hosts
#           echo "${{ secrets.KNOWN_HOSTS }}" &> /home/runner/.ssh/known_hosts
#           chmod 700 /home/runner/ssh_key
#           ssh -i ~/ssh_key root@64.227.147.124 -t "cd week-25-ci-next-app/ && git pull origin main && export PATH=/root/.nvm/versions/node/v22.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && npm install -g pnpm && pnpm install && pnpm run build && pm2 restart fe-sever && pm2 restart http-sever && pm2 restart ws-sever"



name: Deploy to dev environment
on:
  push:
    branches: [main]

jobs:
  redploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the dev cluster

    steps:
      - name: Deploy via SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 600 ~/ssh_key

          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.DEV_VM_IP }} >> ~/.ssh/known_hosts


          ssh -i ~/ssh_key farazyt12@${{ secrets.DEV_VM_IP }} -t "
            export PATH=/home/farazyt12/.nvm/versions/node/v22.20.0/bin/node&&
            cd ci-cd/ &&
            git pull origin main &&
            npm install -g pnpm &&
            pnpm install &&
            pnpm run build &&
            pm2 restart fe-server &&
            pm2 restart http-server &&
            pm2 restart ws-server
          "

